name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        include:
          - python-version: 3.11
            django-version: Django==4.2

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install required system requirements
      run: |
        sudo apt install pkg-config libxml2-dev libxmlsec1-dev
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ${{ matrix.django-version }}
        pip install -r example/requirements.txt
        pip install -e .[mssso]
    - name: Flake
      run: |
        flake8 --config .config/flake8 --ignore E1,E23,W503 auth_token
    - name: Run Tests
      run: |
        cd example
        coverage run --omit */site-packages/*,*/migrations/*,*/lib/* manage.py test app.tests --settings=dj.settings.test -v 2
    - name: Coveralls
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel: true
        flag-name: Unit Test

  coveralls_finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
